# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajbH26BdkwMqIfikpozqwG3bEbtp6Cv5
"""

import streamlit as st
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# ---------------------------
# Page Configuration
# ---------------------------
st.set_page_config(
    page_title="Iris Flower Clustering",
    page_icon="🌸",
    layout="wide"
)

st.title("🌸 Iris Flower Clustering using K-Means")
st.write("This app clusters Iris flowers based on **Petal Length** and **Petal Width**.")

# ---------------------------
# Load Dataset
# ---------------------------
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Keep only required features
df = df[['petal length (cm)', 'petal width (cm)']]

# ---------------------------
# Train KMeans Model
# ---------------------------
kmeans = KMeans(n_clusters=3, random_state=42)
df["Cluster"] = kmeans.fit_predict(df)

# ---------------------------
# Sidebar Input
# ---------------------------
st.sidebar.header("Predict Cluster")

petal_length = st.sidebar.slider(
    "Petal Length (cm)",
    float(df["petal length (cm)"].min()),
    float(df["petal length (cm)"].max()),
    4.5
)

petal_width = st.sidebar.slider(
    "Petal Width (cm)",
    float(df["petal width (cm)"].min()),
    float(df["petal width (cm)"].max()),
    1.5
)

# ---------------------------
# Predict Cluster
# ---------------------------
prediction = kmeans.predict([[petal_length, petal_width]])[0]

st.subheader("Prediction")

st.success(f"The flower belongs to **Cluster {prediction}**")

# ---------------------------
# Visualization
# ---------------------------
fig, ax = plt.subplots(figsize=(8,6))

colors = ['red', 'green', 'blue']

for i in range(3):
    cluster_data = df[df["Cluster"] == i]
    ax.scatter(
        cluster_data["petal length (cm)"],
        cluster_data["petal width (cm)"],
        label=f"Cluster {i}",
        color=colors[i]
    )

# User point
ax.scatter(
    petal_length,
    petal_width,
    color="black",
    marker="*",
    s=250,
    label="Your Input"
)

# Centroids
centers = kmeans.cluster_centers_
ax.scatter(
    centers[:,0],
    centers[:,1],
    marker="X",
    s=250,
    color="gold",
    label="Centroids"
)

ax.set_xlabel("Petal Length (cm)")
ax.set_ylabel("Petal Width (cm)")
ax.legend()

st.pyplot(fig)

# ---------------------------
# Dataset
# ---------------------------
st.subheader("Dataset")
st.dataframe(df)

# ---------------------------
# Elbow Method
# ---------------------------
st.subheader("Elbow Method")

sse = []
k_values = range(1, 10)

for k in k_values:
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(df[['petal length (cm)', 'petal width (cm)']])
    sse.append(model.inertia_)

fig2, ax2 = plt.subplots(figsize=(6,4))
ax2.plot(k_values, sse, marker='o')
ax2.set_xlabel("Number of Clusters (K)")
ax2.set_ylabel("SSE")
ax2.set_title("Elbow Method")

st.pyplot(fig2)